branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: musiciodemo-node
global:
  application_name: musiciodemo
  branch: null
  default_ec2_keyname: aws_millenuum
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: musiciodemo-backend
  sc: git
  workspace_type: Application
